# Operating System: Windows, macOS
# Java Versions: Java 8
# Tests: Only run Unit Tests
# Reports: Unit test report
name: JAVA CI Unit tests with Maven in Windows & MacOS
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
        - java: 8
    name: Build with Java ${{ matrix.java }}  on  ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml','**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        mvn verify 
      if: ${{ always () }}
    - name: ArchiveJUnitReport
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
       name: surefire-report-jdk-${{ matrix.java }}-${{ matrix.os }}
       path: '**/target/site'
    - name: ArchiveLogs
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
         name: log-files-${{ matrix.os }}
         path: './*.log'

