# Operating System: Ubuntu
# Java Versions: Java 8, Java 11, and Java 17
# Coverage and Mutation is tested only on java 8 
# Tests: All tests (Unit)
# Reports: Unit test report , Coverage coversall and Mutation Testing
name: JAVA CI Unit tests, Mutation tests and Coveralls with Maven in Linux
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - java: 8
          additional-maven-args: "-Pmutation-testing-with-coverage -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"
        - java: 11
        - java: 17
          additional-maven-args: "-Pjacoco"
    name: Build with Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml','**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        xvfb-run mvn verify ${{matrix.additional-maven-args}}  
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}} 
    - name: Generate JUnit Report
      run: >
        mvn surefire-report:report-only site:site -DgenerateReport=false
      if: ${{ always () }}
    - name: ArchiveJUnitReport
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
       name: surefire-report-jdk-${{ matrix.java }}
       path: '**/target/site'
    - name: ArchiveJaCoCoReport
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
          name: jacoco-report-jdk-${{ matrix.java }}
          path: '**/target/site/jacoco'
    - name: ArchivePitReport
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
          name: pit-report-jdk-${{ matrix.java }}
          path: '**/target/pit-reports'
    - name: ArchiveLogs
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
         name: log-files
         path: './*.log'

